# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-15 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20190115_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelled_img',
            name='image_path',
            field=models.CharField(max_length=300),
        ),
    ]
