# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-17 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20190115_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_name',
            field=models.CharField(default='x', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='time_stamp',
            field=models.CharField(default='xx', max_length=50),
            preserve_default=False,
        ),
    ]
