# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-25 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='glt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=50000)),
                ('url', models.CharField(max_length=500000000)),
            ],
        ),
    ]
